### ISSUE TITLE
Pass props down to Scroll component

### ISSUE THREAD

**Issue by TravisHall** [ismamz/Sticky.framerfx#1]
Hi Ismael 

Thanks for your work on this component, super useful. I'm using it for a project that involves using code overrides to apply other effects based on scroll position.

It would be good if the `Sticky` component passed down props to the scroll component, this would make it more extensible. 

Thanks

**Comment by ismamz** [comment]
Hi! I've just update the package to add support for code overrides. Let me know how it works for you!

**Comment by TravisHall** [comment]
Perfect, works well with overrides now. Thanks!
