### ISSUE TITLE
Error in Sticky.tsx

### ISSUE THREAD

**Issue by mishagordin** [ismamz/Sticky.framerfx#3]
Dear Developer. 
I'm trying to implement a sticky package and when it comes to "stick the frame" the prototype shows the red screen 
Error in sticky.tsx
«undefined is not an object (evaluating 'stuck.props.children[0].props')»
how can i fix it ? 
thanks in advance 
<img width="334" alt="Screenshot 2020-10-16 at 16 14 43" src="https://user-images.githubusercontent.com/52451344/96269478-b63a0c00-0fca-11eb-8411-291c886c660e.png">

**Comment by ismamz** [comment]
Hi @mishagordin you can update the package and it will work!
